all:test01 test02 test04 

CFLAGS+=-g
test01: test01.c
	${cc} ${cflags} -o $@ $< -lpthread

test02: test02.c
	${CC} ${CFLAGS} -o $@ $< -lpthread


test04: test04.c
	${CC} ${CFLAGS} -o $@ $< -lpthread

